
GET http://localhost:5000/api/auth/
###


POST http://localhost:5000/api/auth/register
Content-Type: application/json 

{
    "email": "hoangtranthong04@gmail.com",
    "password": "abcde"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json 

{
    "username": "sirochanhday",
    "password": "12345"
}

###
POST http://localhost:5000/api/post/postofuser
Content-Type: application/json 

{
    "id": "6583db85535182c1674fb11e"
}

###
POST http://localhost:5000/api/auth/following
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZjN2U0OWEwMmFkNTllZjU5ZDU1YWQiLCJpYXQiOjE3MDM3ODU1ODB9.SN0fyLRv2427YRI4U52WtlAsE_K0PacmEtRmMMIIQjA

{
    "followingId": "65728602fe9961d3ceba7338",
    "followerId": "656c7e49a02ad59ef59d55ad"
}


###
GET http://localhost:5000/api/auth/alluser

###
POST http://localhost:5000/api/auth/updateadmin

###
POST http://localhost:5000/api/auth/getuser
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZjN2U0OWEwMmFkNTllZjU5ZDU1YWQiLCJpYXQiOjE3MDMwNTQ3NDN9.o2clB8uzKkWKnWOxpvp8vYtfKQ5Vaq0CFuYv0jsDxME

{
    "user_id": "6583db85535182c1674fb11e"
}


###
GET http://localhost:5000/api/post/allpost

###
POST http://localhost:5000/api/post/detailpost
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZjN2U0OWEwMmFkNTllZjU5ZDU1YWQiLCJpYXQiOjE3MDMwNTQ3NDN9.o2clB8uzKkWKnWOxpvp8vYtfKQ5Vaq0CFuYv0jsDxME

{
    "id": "657fb2269d0c77581b09fa97"
}

###
GET http://localhost:5000/api/post/newestpostlarge

###
GET http://localhost:5000/api/post/newestpost

###
GET http://localhost:5000/api/post/657e64ce7add08a3ea88f64a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZjN2U0OWEwMmFkNTllZjU5ZDU1YWQiLCJpYXQiOjE3MDI4MDg5MzJ9.YoWG8CZoof9POhUPxxVKJ9Cn6Z3eArYCj0XK62MFr48

###
POST http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZjN2U0OWEwMmFkNTllZjU5ZDU1YWQiLCJpYXQiOjE3MDE3ODMzMzV9.Mst9G8_pW1Mlh0xkcZL04HGRnZ7z7Qle5OWOguxp4nc

{
    "title": "title3",
    // "category": "Fitness",
    "content": "content3"
}


###
GET http://localhost:5000/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZjN2U0OWEwMmFkNTllZjU5ZDU1YWQiLCJpYXQiOjE3MDE3ODMzMzV9.Mst9G8_pW1Mlh0xkcZL04HGRnZ7z7Qle5OWOguxp4nc


###
PUT http://localhost:5000/api/post/658d5f4865e9de8538a7ffb9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZjN2U0OWEwMmFkNTllZjU5ZDU1YWQiLCJpYXQiOjE3MDE3ODMzMzV9.Mst9G8_pW1Mlh0xkcZL04HGRnZ7z7Qle5OWOguxp4nc

{
    "title": "Update title2",
    //"category": "Lifestyle",
    "content": "Update content2"
}


###
DELETE http://localhost:5000/api/post/658394fd405fa901793bcce3

###
DELETE http://localhost:5000/api/auth/656c83a60d0ebca3c5d78af9

###
PUT http://localhost:5000/api/auth/65728602fe9961d3ceba7338
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTY5ODlhNjEzOGMwODRiZGUzMTdiZjEiLCJpYXQiOjE3MDE0NDE3Nzd9.V-RS2Nk6AqEIH_IwmOzP4CLQcVgD07rHItckwzkJjbg

{
    "username": "thon",
    "email": "thong@gmail.com",
    "password": "123",
    "contact": "",
    "description": "description"
}
